{
    "openapi": "3.0.1",
    "info": {
        "title": "Slack Web API",
        "description": "One way to interact with the Slack platform is its HTTP RPC-based Web API, a collection of methods requiring OAuth 2.0-based user, bot, or workspace tokens blessed with related OAuth scopes.",
        "contact": {
            "name": "Slack developer relations",
            "url": "https://api.slack.com/support"
        },
        "version": "1.7.0"
    },
    "servers": [
        {
            "url": "https://slack.com/api"
        }
    ],
    "tags": [],
    "paths": {
        "/chat.postMessage": {
            "post": {
                "tags": [
                    "chat"
                ],
                "description": "Sends a message to a channel.",
                "operationId": "chat_postMessage",
                "security": [
                    {
                        "slackAuth": [
                            "chat:write:user",
                            "chat:write:bot"
                        ]
                    }
                ]
            }
        },
        "/conversations.history": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Fetches a conversation's history of messages and events.",
                "operationId": "conversations_history",
                "security": [
                    {
                        "slackAuth": [
                            "channels:history",
                            "groups:history",
                            "im:history",
                            "mpim:history"
                        ]
                    }
                ]
            }
        },
        "/conversations.info": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Retrieve information about a conversation.",
                "operationId": "conversations_info",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.join": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Joins an existing conversation.",
                "operationId": "conversations_join",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write"
                        ]
                    }
                ]
            }
        },
        "/conversations.list": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Lists all channels in a Slack team.",
                "operationId": "conversations_list",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.members": {
            "get": {
                "tags": [
                    "conversations"
                ],
                "description": "Retrieve members of a conversation.",
                "operationId": "conversations_members",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/conversations.open": {
            "post": {
                "tags": [
                    "conversations"
                ],
                "description": "Opens or resumes a direct message or multi-person direct message.",
                "operationId": "conversations_open",
                "security": [
                    {
                        "slackAuth": [
                            "channels:write",
                            "groups:write",
                            "im:write",
                            "mpim:write"
                        ]
                    }
                ]
            }
        },
        "/users.conversations": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "List conversations the calling user may access.",
                "operationId": "users_conversations",
                "security": [
                    {
                        "slackAuth": [
                            "channels:read",
                            "groups:read",
                            "im:read",
                            "mpim:read"
                        ]
                    }
                ]
            }
        },
        "/users.info": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Gets information about a user.",
                "operationId": "users_info",
                "security": [
                    {
                        "slackAuth": [
                            "users:read"
                        ]
                    }
                ]
            }
        },
        "/users.list": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Lists all users in a Slack team.",
                "operationId": "users_list",
                "security": [
                    {
                        "slackAuth": [
                            "users:read"
                        ]
                    }
                ]
            }
        },
        "/users.lookupByEmail": {
            "get": {
                "tags": [
                    "users"
                ],
                "description": "Find a user with an email address.",
                "operationId": "users_lookupByEmail",
                "security": [
                    {
                        "slackAuth": [
                            "users:read.email"
                        ]
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "slackAuth": {
                "type": "oauth2",
                "flows": {
                    "authorizationCode": {
                        "authorizationUrl": "https://slack.com/oauth/authorize",
                        "tokenUrl": "https://slack.com/api/oauth.access",
                        "scopes": {
                            "admin": "admin",
                            "admin.apps:read": "admin.apps:read",
                            "admin.apps:write": "admin.apps:write",
                            "admin.conversations:read": "admin.conversations:read",
                            "admin.conversations:write": "admin.conversations:write",
                            "admin.invites:read": "admin.invites:read",
                            "admin.invites:write": "admin.invites:write",
                            "admin.teams:read": "admin.teams:read",
                            "admin.teams:write": "admin.teams:write",
                            "admin.usergroups:read": "admin.usergroups:read",
                            "admin.usergroups:write": "admin.usergroups:write",
                            "admin.users:read": "admin.users:read",
                            "admin.users:write": "admin.users:write",
                            "authorizations:read": "authorizations:read",
                            "bot": "Bot user scope",
                            "calls:read": "calls:read",
                            "calls:write": "calls:write",
                            "channels:history": "channels:history",
                            "channels:manage": "channels:manage",
                            "channels:read": "channels:read",
                            "channels:write": "channels:write",
                            "chat:write": "chat:write",
                            "chat:write:bot": "Author messages as a bot",
                            "chat:write:user": "Author messages as a user",
                            "conversations:history": "conversations:history",
                            "conversations:read": "conversations:read",
                            "conversations:write": "conversations:write",
                            "dnd:read": "dnd:read",
                            "dnd:write": "dnd:write",
                            "emoji:read": "emoji:read",
                            "files:read": "files:read",
                            "files:write:user": "files:write:user",
                            "groups:history": "groups:history",
                            "groups:read": "groups:read",
                            "groups:write": "groups:write",
                            "identity.basic": "identity.basic",
                            "im:history": "im:history",
                            "im:read": "im:read",
                            "im:write": "im:write",
                            "links:write": "links:write",
                            "mpim:history": "mpim:history",
                            "mpim:read": "mpim:read",
                            "mpim:write": "mpim:write",
                            "none": "No scope required",
                            "pins:read": "pins:read",
                            "pins:write": "pins:write",
                            "reactions:read": "reactions:read",
                            "reactions:write": "reactions:write",
                            "reminders:read": "reminders:read",
                            "reminders:write": "reminders:write",
                            "remote_files:read": "remote_files:read",
                            "remote_files:share": "remote_files:share",
                            "remote_files:write": "remote_files:write",
                            "rtm:stream": "rtm:stream",
                            "search:read": "search:read",
                            "stars:read": "stars:read",
                            "stars:write": "stars:write",
                            "team:read": "team:read",
                            "tokens.basic": "tokens.basic",
                            "usergroups:read": "usergroups:read",
                            "usergroups:write": "usergroups:write",
                            "users.profile:read": "users.profile:read",
                            "users.profile:write": "users.profile:write",
                            "users:read": "users:read",
                            "users:read.email": "users:read.email",
                            "users:write": "users:write",
                            "workflow.steps:execute": "workflow.steps:execute"
                        }
                    }
                }
            }
        }
    }
}