# constant for HAR files
HAR_LOG = "log"
HAR_ENTRIES = "entries"
HAR_QUERY = "queryString"
HAR_POSTDATA = "postData"
HAR_PARAMS = "params"
HAR_TEXT = "text"
HAR_NAME = "name"
HAR_VALUE = "value"
HAR_CONTENT = "content"
HAR_RESPONSE = "response"
HAR_REQUEST = "request"
HAR_METHOD = "method"
HAR_URL = "url"
HAR_MIME = "mimeType"